apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
type: Opaque
stringData:
  client-id: "PLACEHOLDER_CLIENT_ID"
  client-secret: "PLACEHOLDER_CLIENT_SECRET"
  issuer-uri: "https://accounts.google.com" # Example
